;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		LaTeX-babel-insert-hyphen
		LaTeX-environment
		TeX-insert-backslash
		TeX-insert-dollar
		TeX-insert-sub-or-superscript
		beginning-of-visual-line
		c-electric-brace
		c-electric-colon
		c-electric-delete-forward
		c-electric-lt-gt
		c-electric-paren
		c-electric-pound
		c-electric-semi&comma
		c-electric-slash
		c-electric-star
		c-indent-line-or-region
		comment-dwim
		comment-region
		delete-horizontal-space
		dired-next-line
		dired-previous-line
		end-of-buffer
		end-of-visual-line
		eval-last-sexp
		eval-print-last-sexp
		forward-sentence
		indent-for-tab-command
		kill-region
		kill-visual-line
		mark-word
		matlab-comment
		matlab-electric-comment
		matlab-linefeed
		phi-search
		reindent-then-newline-and-indent
		rm-kill-region
		semantic-complete-self-insert
		sgml-slash
		sh-end-of-command
		wdired-upcase-word
		))

(setq mc/cmds-to-run-once
      '(
		beginning-of-buffer
		compile
		describe-key
		dired
		goto-line
		ido-find-file
		ido-switch-buffer
		ido-switch-buffer-other-window
		kill-rectangle
		make-default
		mouse-save-then-kill
		multiple-cursors-mode
		scroll-other-window
		view-lossage
		wdired-finish-edit
		))
