;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	TeX-insert-backslash
	TeX-insert-sub-or-superscript
	c-electric-brace
	c-electric-colon
	c-electric-delete-forward
	c-electric-lt-gt
	c-electric-paren
	c-electric-pound
	c-electric-semi&comma
	c-electric-slash
	c-electric-star
	c-indent-line-or-region
	comment-dwim
	delete-horizontal-space
	eval-print-last-sexp
	indent-for-tab-command
	kill-region
	mark-word
	matlab-comment
	matlab-electric-comment
	matlab-linefeed
	rm-kill-region
	semantic-complete-self-insert
	sgml-slash
	))

(setq mc/cmds-to-run-once
      '(
	beginning-of-buffer
	describe-key
	dired
	goto-line
	ido-find-file
	ido-switch-buffer
	ido-switch-buffer-other-window
	kill-rectangle
	make-default
	mouse-save-then-kill
	multiple-cursors-mode
	scroll-other-window
	))
